# Generated by Django 5.1 on 2025-05-13 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_superuser': True, 'role': 'user_marker'}, on_delete=django.db.models.deletion.CASCADE, related_name='marker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_superuser': True, 'role': 'user_supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validatorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_superuser': True, 'role': 'user_validator'}, on_delete=django.db.models.deletion.CASCADE, related_name='validator_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
