# Generated by Django 5.1 on 2025-05-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_markerprofile_user_alter_supplierprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='role_required_unless_superuser',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['user_marker', 'user_validator', 'user_supplier'])), name='role_required'),
        ),
    ]
