# Generated by Django 5.1 on 2025-05-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_role_required_unless_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user_marker', 'Маркировщик'), ('user_validator', 'Валидатор'), ('user_supplier', 'Поставщик данных')], default='user_marker', max_length=20, null=True, verbose_name='Роль'),
        ),
    ]
