# Generated by Django 5.1 on 2025-05-21 18:45

import django.db.models.deletion
import markup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(help_text='Файл в формате .npy', upload_to=markup.models.ecg_file_path, verbose_name='Файл с данными ЭКГ')),
                ('sample_rate', models.PositiveIntegerField(default=500, verbose_name='Частота дискретизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('markup_assignments_count', models.PositiveIntegerField(default=0, help_text='Сколько раз этот сигнал был взят в работу или успешно размечен.', verbose_name='Количество назначений на разметку')),
            ],
            options={
                'verbose_name': 'Сигнал ЭКГ',
                'verbose_name_plural': 'Сигналы ЭКГ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markup.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup_data', models.JSONField(default=list, verbose_name='Данные разметки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('for_validation', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает в')),
                ('diagnoses', models.ManyToManyField(blank=True, related_name='markups', to='markup.diagnosis', verbose_name='Диагнозы')),
            ],
            options={
                'verbose_name': 'Разметка',
                'verbose_name_plural': 'Разметки',
            },
        ),
    ]
