# Generated by Django 5.1 on 2025-05-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные ЭКГ')),
                ('sample_rate', models.PositiveIntegerField(default=500, verbose_name='Частота дискретизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Сигнал ЭКГ',
                'verbose_name_plural': 'Сигналы ЭКГ',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markup.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup_data', models.JSONField(verbose_name='Данные разметки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('for_validation', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('diagnoses', models.ManyToManyField(related_name='markups', to='markup.diagnosis', verbose_name='Диагнозы')),
            ],
            options={
                'verbose_name': 'Разметка',
                'verbose_name_plural': 'Разметки',
            },
        ),
    ]
