# Generated by Django 5.1 on 2025-05-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markup', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markup',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_markups', to='users.markerprofile', verbose_name='Маркировщик'),
        ),
        migrations.AddField(
            model_name='markup',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_markups', to='users.validatorprofile', verbose_name='Валидатор'),
        ),
        migrations.AddField(
            model_name='signal',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_signals', to='users.supplierprofile', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='markup',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='markup.signal', verbose_name='Сигнал ЭКГ'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_diagnose_name_per_parent'),
        ),
    ]
