# Generated by Django 5.1 on 2025-04-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='diseases',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_disease_name_per_parent'),
        ),
    ]
