# Generated by Django 5.1 on 2025-05-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markup',
            name='marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_markups', to='users.markerprofile', verbose_name='Маркировщик'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_signals', to='users.supplierprofile', verbose_name='Поставщик'),
        ),
    ]
