# Generated by Django 5.1 on 2025-05-14 18:40

import markup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='data',
        ),
        migrations.AddField(
            model_name='signal',
            name='data_file',
            field=models.FileField(
                help_text='Файл в формате .npy',
                upload_to=markup.models.ecg_file_path,
                verbose_name='Файл с данными ЭКГ'
            ),
        ),
        migrations.AddField(
            model_name='signal',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
    ]
