# Generated by Django 5.1 on 2025-05-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0003_remove_signal_data_signal_data_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['created_at'], 'verbose_name': 'Сигнал ЭКГ', 'verbose_name_plural': 'Сигналы ЭКГ'},
        ),
        migrations.AddField(
            model_name='markup',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает в'),
        ),
        migrations.AddField(
            model_name='signal',
            name='markup_assignments_count',
            field=models.PositiveIntegerField(default=0, help_text='Сколько раз этот сигнал был взят в работу или успешно размечен.', verbose_name='Количество назначений на разметку'),
        ),
        migrations.AlterField(
            model_name='markup',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, related_name='markups', to='markup.diagnosis', verbose_name='Диагнозы'),
        ),
        migrations.AlterField(
            model_name='markup',
            name='markup_data',
            field=models.JSONField(default=list, verbose_name='Данные разметки'),
        ),
    ]
