# Generated by Django 5.1 on 2025-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0003_alter_markup_marker_alter_signal_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='markup',
            name='is_diagnoses_confirmed',
            field=models.BooleanField(default=False, verbose_name='Диагнозы подтверждены'),
        ),
        migrations.AddField(
            model_name='markup',
            name='is_markup_annotations_confirmed',
            field=models.BooleanField(default=False, verbose_name='Разметка ЭКГ подтверждена'),
        ),
    ]
