# Generated by Django 5.1 on 2025-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0004_markup_is_diagnoses_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markup',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_validation', 'Ожидает проверки'), ('for_validation', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
