# Generated by Django 5.1 on 2025-06-10 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0005_alter_markup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='sample_rate',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)], verbose_name='Частота дискретизации'),
        ),
    ]
